name: swipeable_page_route
description: '🔙 Swipe to navigate back and admire beautifully morphing widgets'
version: 0.2.6
homepage: https://github.com/JonasWanke/swipeable_page_route

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  black_hole_flutter: ^1.0.3
  collection: ^1.17.1
  flutter:
    sdk: flutter
  list_diff: ^2.0.1
  meta: ^1.9.1

dev_dependencies:
  flutter_lints: ^2.0.1
